CREATE TABLE IF NOT EXISTS dwd_tempdata 
	(
	station_id INTEGER UNSIGNED NOT NULL,
	dt DATETIME NOT NULL,
	temp INTEGER NOT NULL
	);

CREATE TABLE IF NOT EXISTS dwd_station
	(
	station_id_u INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	station_id INTEGER UNSIGNED NOT NULL,
	lat DECIMAL(10,5) NOT NULL,
	lon DECIMAL(10,5) NOT NULL,
	dt_start DATETIME NOT NULL,
	dt_end DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(station_id_u)
	);
	